[build]
  command = "npm ci && npm run build"
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
  sitemapPath = "/sitemap.xml"
  providers = ["google","yandex"]
  ignorePeriod = 0
