[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
  sitemapPath = "/sitemap.xml"
  providers = ["google","yandex"]
  ignorePeriod = 0
